name: MysqlExperienceBridge
main: net.craftersland.bridge.exp.Exp
version: 1.7.1
author: CraftersLand
website: www.craftersland.net
load: STARTUP
api-version: 1.13
description: Sync your experience over many servers using MySQL.