name: MysqlExperienceBridge
main: net.craftersland.bridge.exp.Exp
version: 1.4.1
author: CraftersLand
website: www.craftersland.net
load: STARTUP
description: Sync your experience over many servers using MySQL.